apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  initTimeout: 1m
  metadata:
    - name: redisHost
      value: "redis-master:6379"
    - name: redisPassword
      value: rC3rlKuJyw
    - name: keyPrefix
      value: none 